logging:
  level:
    org.springframework: INFO

spring:
  profiles:
    active: @spring.profiles.active@

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080