#Create a docker compose file for mysql database and jenkins file
version: '3.7'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jsonplaceholder
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "9091:9091"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JENKINS_OPTS: --httpPort=9091
volumes:
  jenkins_home: