version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "9091:9091"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JENKINS_OPTS: --httpPort=9091
volumes:
  jenkins_home: